### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by giordano** [byuflowlab/VortexLattice.jl#18]
This package has no license file.  Note that packages registered in General are [expected to have an OSI-approved license](https://github.com/JuliaRegistries/General/blob/5df36a5987db30b5c75ab3c0959a4a9ba95cf6bb/README.md#registering-a-package-in-general), even if this isn't currently automatically enforced

CC: @taylormcd

**Comment by taylormcd** [comment]
My bad, I usually add the license during package creation so I didn't think to check if it was there.  I just added it.

**Comment by giordano** [comment]
Thanks!
